/*
 * File: app/view/Form.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('JWF.view.Form', {
    extend: 'Ext.Panel',

    config: {
        padding: '15 15 15 15',
        scrollable: false,
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'New Jog',
                items: [
                    {
                        xtype: 'button',
                        id: 'addRunBackBtn',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'fieldset',
                items: [
                    {
                        xtype: 'textfield',
                        id: 'locationField',
                        placeHolder: 'Where?'
                    },
                    {
                        xtype: 'textfield',
                        id: 'distanceField',
                        placeHolder: 'How Many Miles?'
                    }
                ]
            },
            {
                xtype: 'button',
                id: 'addRunButton',
                ui: 'facebook',
                text: 'Add Jog'
            }
        ]
    }

});